remote_theme: pages-themes/slate@v0.2.0
title: HUBOT Chair
description: Human-Centered Programming by Demonstration for Collaborative Industrial Robotics
url: "https://pellierd.github.io"
baseurl: "/miai-hubot-chair"

author:
  name: MIAI Hubot Team
  github: pellierd
  email: damien.pellier@univ-grenoble-alpes.fr
