site_name: "Hubot MIAI Chair"
site_description: Hubot MIAI Chair
site_author: Damien Pellier
site_url: https://pellierd.github.io/miai-hubot-chair/
copyright: Copyright © 2025 Damien Pellier

theme:
  name: material
  favicon: images/favicon.png
  features:
    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.sticky
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode sombre
    - scheme: slate
      primary: blue-grey
      accent: grey
      toggle:
        icon: material/weather-night
        name: Basculer en mode clair

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: false
      toc_depth: 0

extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Publications: https://cv.hal.science/pellier
  - Demonstrations: https://www.youtube.com/channel/UC6oqhcs8tBPCo8RH4B_6OPA
  - Softwares and Tools: research/softwares.md
  - Supervising: research/supervising.md
  - Open Positions: research/open-positions.md
  - Contact: contact.md
