name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # déploie quand on pousse sur la branche main

permissions:
  contents: write  # nécessaire pour pousser sur gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force

